### ISSUE TITLE
release.js not working unless SUDO; even then, gives 404 not found

### ISSUE THREAD

**Issue by kristelfung** [nodee-apps/cms#11]
Hey there,

I have downloaded all necessary files, used npm install to install necessary packages and started my local MongoDB server. However, when I try to start the server with `node release.js`, the following error occurs:

`Error: listen EACCES 0.0.0.0:80 Error: listen EACCES 0.0.0.0:80`

I can start the server with `sudo node release.js`, but when I try to visit http://0.0.0.0:80/, the page returns a 404: Not found error. 

Any way to fix this? Thank you!

**Comment by matusszabo** [comment]
Hi,
1. In UNIX-like systems, non-root users are unable to bind to ports lower than 1024.
2. 0.0.0.0 is not an actual IP that you can reach. Although it means bind to all IPs, or any IP. So no wonder it works for 127.0.0.1.
3. 404: Not found error, means you have no web page set yet (http://nodejsenterprise.com/docs/nodejs-cms/tutorial/creating-new-website)
