### ISSUE TITLE
Missing index

### ISSUE THREAD

**Issue by Masner** [nodee-apps/cms#12]
Hello,
first of all i would like to give you a thumbs up (and star).
This CMS seems to be really outstanding. I've tried you demo and it really fits my needs.

But i have encountered an issue. 
I am getting 404 on debug and release. 
I followed your guide and everything seems to be just fine. CMS is connected to Mongo and is up and running without any errors (worst thing i got is No repository fields from npm when running npm install)

I think i am having similar problem as `https://github.com/nodee-apps/cms/issues/11`, but i am trying to run your cms on windows. 

When i am trying to access /admin i am getting error pasted bellow.

So do i have to create index.html or am i missing something ?

Thanks for your help and time

Best Regards
David

> Cannot render template: View "tmp/enterprise-admin/views/index.html" compilation failed <-- View engine compileSync: reading template file failed <-- ENOENT: no such file or directory, open 'D:\Websites\Nodee\tmp\enterprise-admin\views\index.html'
> 
> Error: View "tmp/enterprise-admin/views/index.html" compilation failed <-- View engine compileSync: reading template file failed <-- ENOENT: no such file or directory, open 'D:\Websites\Nodee\tmp\enterprise-admin\views\index.html'
>     at isValidView (D:\Websites\Nodee\node_modules\enterprise-view\lib\view.js:262:45)
>     at getCompiledSync (D:\Websites\Nodee\node_modules\enterprise-view\lib\view.js:381:9)
>     at Object.renderViewSync [as renderSync](D:WebsitesNodeenode_modulesenterprise-viewlibview.js:352:23)
>     at Object.view (eval at <anonymous> (D:\Websites\Nodee\node_modules\total.js\index.js:3015:82), <anonymous>:169:37)
>     at Object.Controller.view (eval at <anonymous> (D:\Websites\Nodee\node_modules\total.js\index.js:3015:82), <anonymous>:127:25)
>     at Object.index (D:\Websites\Nodee\tmp\enterprise-admin.package\index.js:525:10)
>     at Subscribe.Framework.$load.arr.forEach.arr.forEach.arr.forEach.Framework.log.Framework.logger.Framework.responseStatic.Framework.responseStream.Framework.responseBinary.Framework.responseContent.Framework.mode.Framework._request_continue.self._cors.self._cors.self._cors.Framework.test.Framework._configure.FrameworkPath.exists.Subscribe.urlencoded.Subscribe.doExecute (D:\Websites\Nodee\node_modules\total.js\index.js:9761:23)
>     at Subscribe.Framework.$load.arr.forEach.arr.forEach.arr.forEach.Framework.log.Framework.logger.Framework.responseStatic.Framework.responseStream.Framework.responseBinary.Framework.responseContent.Framework.mode.Framework._request_continue.self._cors.self._cors.self._cors.Framework.test.Framework._configure.FrameworkPath.exists.Subscribe.urlencoded.Subscribe.execute (D:\Websites\Nodee\node_modules\total.js\index.js:9684:15)
>     at Subscribe.Framework.$load.arr.forEach.arr.forEach.arr.forEach.Framework.log.Framework.logger.Framework.responseStatic.Framework.responseStream.Framework.responseBinary.Framework.responseContent.Framework.mode.Framework._request_continue.self._cors.self._cors.self._cors.Framework.test.Framework._configure.FrameworkPath.exists.Subscribe.urlencoded.Subscribe.prepare (D:\Websites\Nodee\node_modules\total.js\index.js:9727:8)
>     at Subscribe.Framework.$load.arr.forEach.arr.forEach.arr.forEach.Framework.log.Framework.logger.Framework.responseStatic.Framework.responseStream.Framework.responseBinary.Framework.responseContent.Framework.mode.Framework._request_continue.self._cors.self._cors.self._cors.Framework.test.Framework._configure.FrameworkPath.exists.Subscribe.urlencoded.Subscribe.doEnd (D:\Websites\Nodee\node_modules\total.js\index.js:9850:8)
> 
> template: D:\Websites\Nodee/tmp/enterprise-admin/views/index.html
> errno: -4058
> code: ENOENT
> syscall: open
> path: D:\Websites\Nodee\tmp\enterprise-admin\views\index.html
> errlevel: 3

**Comment by matusszabo** [comment]
Hi @Masner, seems like same it is as https://github.com/nodee-apps/cms/issues/10 . Please try it and let us know. thank you.
