### ISSUE TITLE
Redirect instead of login.

### ISSUE THREAD

**Issue by tomasholovsky** [nodee-apps/cms#16]
Register the first user, it appears in the DB correctly, with the role user and admin, I do not see another error, only that it redirects me to the login.

![captura de pantalla de 20170420 132755](https://cloud.githubusercontent.com/assets/15209522/25269025/450b7bd6-267b-11e7-98ef-8e833c120d74.png)

![captura de pantalla de 20170420 132656](https://cloud.githubusercontent.com/assets/15209522/25275353/23f25450-2695-11e7-8079-47e69757e7a5.png)

**Comment by matusszabo** [comment]
Hi, "session-cookie-secure" is set to true in release config. It means that user session cookie will be send from browser to server only when website is using https. Run it in debug mode, or set to false if you are running it on localhost. If you are running in production, we strongly recommend using valid ssl certificates.

**Comment by Beor18** [comment]
Thank you very much.
As matusszabo said in "session-cookie-secure" you have to put false if working on localhost
-----------------------------------------------------------
Muchas gracias.
Como matusszabo dijo en "session-cookie-secure" tienes que poner false si se trabaja en localhost
