### ISSUE TITLE
rendering view failed: Cannot find module 'enterprise-model'

### ISSUE THREAD

**Issue by Beor18** [nodee-apps/cms#17]
Hello

When creating in website structure a page appears the following error that does not find that module, I fixed in the list of packages in case it was like nodee-cms-model.package or something like that and nothing

Could it be that I have some other name inside the Package folder or it just is not?

From already thank you very much!

And sorry for my bad english

---------------------------------------------------------------
Hola
al crear en website structure una página aparece el siguiente error que no encuentra ese modulo, me fije en la lista de paquetes por si estaba como nodee-cms-model.package o algo por el estilo y nada

¿Puede ser que tenga algun otro nombre dentro de la carpeta Package o simplemente no esta?

Desde ya muchas gracias!

y perdon por mi ingles malo.

![captura de pantalla de 2017-04-21 13 29 17](https://cloud.githubusercontent.com/assets/15000248/25287138/a5760642-2696-11e7-96c6-c8ed648911a0.png)

**Comment by matusszabo** [comment]
Hi @Beor18 , there was old dependencies left in views, pull and try again please.
