### ISSUE TITLE
Unable to create documents - empty template dropdown

### ISSUE THREAD

**Issue by MariusStuparu** [nodee-apps/cms#2]
When trying to add the root page, the template dropdown is empty (see screenshot) and the Create button is disabled. The modal.templates for ngRepeat is not populated (second screenshot).

[No templates screenshot](http://screencast.com/t/eshQeNSPYK)

[ngRepeat not populated](http://screencast.com/t/6upMox4Ua)

I have created an empty template, as you can see in the screenshot below. I even tried different file names:

[Template created](http://screencast.com/t/a1aI3PMO7en)

**Comment by matusszabo** [comment]
Ok, you done it right. By default, when creating page, cms is searching for templates in views/pages folder, and when creating widget in views/widgets. I will create empty folders "pages" and "widgets", maybe with one layout, page, and widget template in this project.

**Comment by MariusStuparu** [comment]
Yes, some defaults would be best, to get a starting point.

**Comment by matusszabo** [comment]
Added, default template examples.
