### ISSUE TITLE
Ability to add Credit info to Images

### ISSUE THREAD

**Issue by kadosh1000** [nodee-apps/cms#5]
The ability to credit images and specify their source is missing, a lot of websites uses images from various range of origins and the ability to credit images is mandatory

**Comment by tomasholovsky** [comment]
Hi @kadosh1000. You can easily do this by setting up WIDGET.
Visit our DOCS > http://nodejsenterprise.com/docs/nodejs-cms/images. You will see something similar. Thumbnail has 2 different image sizes and name. You need to input them, when you upload image (see enclosed screenshot). 
To add images with link to its source create a widget. Add Editors for specifying source link of the image. Then set up View Mapping to save image source text and link properly.
![screen shot 2016-02-23 at 15 42 46](https://cloud.githubusercontent.com/assets/15209522/13255945/d630ccd6-da48-11e5-80b4-512d6df00f12.png)

**Comment by kadosh1000** [comment]
@tomasholovsky the thing is that the credits will always be the same for an image, and each image will probable be used more than once in multiple pages. I don't want to specify each time i use an image its credit but to get it from the image itself.

**Comment by matusszabo** [comment]
Hi @kadosh1000, if this will be repeatable behaviour, you can do it on server-side using controller in widget template (parse image url and create link to website where image is from). But in mostly cases preferred way is do it on client-side with jquery or another lib. Maybe there is some jquery plugin made already.
